#! /usr/bin/python3 

times = 80

print ("[1]:Creating a tuple, Method 1") 
print ("Empty tuple") 
T = () 
print ("T:", T) 
print ("Tuple with single element") 
T = (1,)
print ("T:", T)
print ("Tuple can contain elements of any objects") 
T = (1, 3.14, "Hello", [1,2,3], {'a':1, 'b':2, 'c':3}, (10,20,30))
print ("T:", T)
print ("Another syntax") 
T = 1, 2, 3.14, [10,20,30]
print ("T:", T)
print ("-" * times)

print ("[2]:Creating a tuple, Method 2") 
T = tuple ("Tuple") 
print ("T:", T)
print ("-" * times)

print ("[3]:Length of a tuple") 
T = tuple ('SPAM') 
print ("T:", T, "len (T):", len (T))
print ("-" * times) 

print ("[4]:Concatenation of tuples") 
T1 = (1, 2, 3)
T2 = ('a', 'b', 'c') 
print ("T1:", T1)
print ("T2:", T2) 
T = T1 + T2 
print ("T:", T) 
print ("-" * times) 

print ("[5]:Multiplication of tuple by a scalar") 
T = (1, 2, 3) 
print ("T:", T) 
T1 = T * 3
print ("T1 after T1 = T * 3, T1:", T1)
print ("-" * times) 

print ("[6]:Indexing a tuple") 
T = tuple ("string") 
print ("T:", T) 
print ("T[0]:", T[0])
print ("T[1]:", T[1]) 
print ("T[2]:", T[2])
print ("T[3]:", T[3])
print ("T[4]:", T[4]) 
print ("T[5]:", T[5]) 
print ("Accessing tuple by for x in") 
for x in T:
    print (x)
print ("Accessing tuple by index") 
for i in range (len (T)):
    print ("T[", i, "]:", T[i])
print ("-" * times) 

print ("[7]:Slicing a tuple") 
T = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
print ("T:", T) 
print ("T[0:4]:", T[0:4])
print ("T[::2]:", T[::2])
print ("T[1::2]:", T[1::2])
print ("T[2:9:3]:", T[2:9:3])
print ("-" * times) 

print ("[8]:Convering tuple into list") 
T = (1, 2, 3, 4, 5) 
print ("T:", T)
L = list (T) 
print ("After L=list (T), L:", L)
print ("-" * times) 

print ("[9]:Sorting a tuple") 
T = (5, 4, 3, 2, 1)
print ("Method 1:Convert to list and invoke sort on list") 
print ("T:", T)
L = list (T) 
print ("L:", L)
L.sort ()
print ("After L.sort (), L:", L)
print ("Method 2:Calling sorted function") 
L = sorted (T) 
print ("After L=sorted (T), L:", L, "type(L):", type (L))
print ("-" * times) 

print ("[11]:Index of an existing data") 
T = (5, 4, 2, 2, 5, 4, 6, 34, 76, 2)
print ("T:", T) 
print ("34 in T:", 34 in T)
print ("345 in T:", 345 in T)
print ("T.index (5):", T.index (5))
print ("T.index (2):", T.index (2))
print ("T.index (2,2):", T.index (2,2))
print ("T.index (2,3):", T.index (2,3))
print ("T.index (2,4):", T.index (2,4))
print ("-" * times) 

print ("[12]:Count method") 
T = (5, 4, 2, 2, 5, 4, 6, 34, 76, 2)
print ("T:", T) 
print ("T.count (5):", T.count (5))
print ("T.count (2):", T.count (2))
print ("T.count(34):", T.count (34))
print ("T.count (500):", T.count (500))
print ("-" * times) 
